baseURL = "https://he-arc.github.io/1242.1-Langage_CPP/"
relativeURLs = false
languageCode = "fr"
title = "HE-Arc 1242.2 Langage CPP"
theme = "book"
enableGitInfo = true

[params]
BookSearch = true
BookRepo = "https://github.com/benoitlecallennec-hes/template_website_course"

[Taxonomies]
  tag = "tags"

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "vs"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
